---
deployment:
  task: 
    - export DEPLOYPATH=/home/coworkingapps/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH